In [11]:
import numpy as np
#some line of codes were AI-assisted from ChatGPT

In [12]:
A = np.array([4., 4, 8, 4,
              4, 5, 3, 7,
              8, 3, 9, 9,
              4, 7, 9, 5]).reshape(4, 4)
b = np.array([1., 2, 3, 4])

In [13]:
n = A.shape[0]
Awork = A.copy().astype(float)
bwork = b.copy().astype(float)

# Forward elimination (no pivoting)
for k in range(n-1):
    pivot = Awork[k, k]
    if abs(pivot) < 1e-19:
        print(f"Zero (or tiny) pivot encountered at row {k}")
        break
    for i in range(k+1, n):
        m = Awork[i, k] / pivot
        Awork[i, k:] -= m * Awork[k, k:]
        bwork[i] -= m * bwork[k]
    print(f"Step {k}, Awork:\n{Awork}\n bwork:{bwork}\n")

print("Upper-triangular Awork (U):\n", Awork)
print("Modified b (after elimination):\n", bwork)

# Back substitution if no zero pivot:
if abs(Awork[-1,-1]) > 1e-19:
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (bwork[i] - np.dot(Awork[i, i+1:], x[i+1:]))/Awork[i,i]
    print("Solution x = ", x)
else:
    print("Cannot back-substitute: last pivot is zero (matrix is singular)")


Step 0, Awork:
[[ 4.  4.  8.  4.]
 [ 0.  1. -5.  3.]
 [ 0. -5. -7.  1.]
 [ 0.  3.  1.  1.]]
 bwork:[1. 1. 1. 3.]

Step 1, Awork:
[[  4.   4.   8.   4.]
 [  0.   1.  -5.   3.]
 [  0.   0. -32.  16.]
 [  0.   0.  16.  -8.]]
 bwork:[1. 1. 6. 0.]

Step 2, Awork:
[[  4.   4.   8.   4.]
 [  0.   1.  -5.   3.]
 [  0.   0. -32.  16.]
 [  0.   0.   0.   0.]]
 bwork:[1. 1. 6. 3.]

Upper-triangular Awork (U):
 [[  4.   4.   8.   4.]
 [  0.   1.  -5.   3.]
 [  0.   0. -32.  16.]
 [  0.   0.   0.   0.]]
Modified b (after elimination):
 [1. 1. 6. 3.]
Cannot back-substitute: last pivot is zero (matrix is singular)


In [14]:
# Forward elimination with partial pivoting
for k in range(n-1):
    # Find pivot row (largest absolute value in column k below k)
    pivot_row = np.argmax(np.abs(Awork[k:, k])) + k
    if pivot_row != k:
        # swap rows in Awork and bwork
        Awork[[k, pivot_row]] = Awork[[pivot_row, k]]
        bwork[[k, pivot_row]] = bwork[[pivot_row, k]]
    pivot = Awork[k, k]
    if abs(pivot) < 1e-19:
        print(f"Zero pivot at step {k} even after pivoting. Matrix is singular.")
        break
    for i in range(k+1, n):
        m = Awork[i, k] / pivot
        Awork[i, k:] -= m * Awork[k, k:]
        bwork[i] -= m * bwork[k]
    print(f"Step {k}, after pivoting Awork:\n{Awork}\nbwork:{bwork}\n")

print("Upper-triangular Awork (U):\n", Awork)
print("Modified b (after elimination):\n", bwork)

# Back substitution if last pivot is nonzero
if abs(Awork[-1,-1]) > 1e-19:
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (bwork[i] - np.dot(Awork[i, i+1:], x[i+1:])) / Awork[i,i]
    print("Solution x =", x)
else:
    print("Cannot back-substitute: last pivot is zero (matrix is singular)")

Step 0, after pivoting Awork:
[[  4.   4.   8.   4.]
 [  0.   1.  -5.   3.]
 [  0.   0. -32.  16.]
 [  0.   0.   0.   0.]]
bwork:[1. 1. 6. 3.]

Step 1, after pivoting Awork:
[[  4.   4.   8.   4.]
 [  0.   1.  -5.   3.]
 [  0.   0. -32.  16.]
 [  0.   0.   0.   0.]]
bwork:[1. 1. 6. 3.]

Step 2, after pivoting Awork:
[[  4.   4.   8.   4.]
 [  0.   1.  -5.   3.]
 [  0.   0. -32.  16.]
 [  0.   0.   0.   0.]]
bwork:[1. 1. 6. 3.]

Upper-triangular Awork (U):
 [[  4.   4.   8.   4.]
 [  0.   1.  -5.   3.]
 [  0.   0. -32.  16.]
 [  0.   0.   0.   0.]]
Modified b (after elimination):
 [1. 1. 6. 3.]
Cannot back-substitute: last pivot is zero (matrix is singular)
